openapi: 3.1.0
info:
  version: 1.0.0
  title: <uygulamanızın adı>
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    <uygulamanızın açıklaması>
tags:
  - Contacts
servers:
  - url: <http://localhost:3000>
  - url: #yayınlanmış siteye bağlantı
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
